import {
	Agreement01Icon,
	AiBrain01Icon,
	Attachment01Icon,
	BookOpen01Icon,
	BrowserIcon,
	Calendar03Icon,
	Certificate01Icon,
	CheckmarkCircle02Icon,
	CircleArrowReload01Icon,
	CloudDownloadIcon,
	CloudIcon,
	CodeIcon,
	ColorPickerIcon,
	CommandIcon,
	DatabaseSearchIcon,
	DiscordIcon,
	File01Icon,
	FileEditIcon,
	Folder01Icon,
	GitBranchIcon,
	GitCommitIcon,
	GitCompareIcon,
	GitMergeIcon,
	GitPullRequestIcon,
	Globe02Icon,
	HeadingIcon,
	HelpCircleIcon,
	InformationCircleIcon,
	Key01Icon,
	KeyboardIcon,
	LanguageSquareIcon,
	Layout01Icon,
	LicenseIcon,
	Link01Icon,
	ListViewIcon,
	Megaphone01Icon,
	Moon02Icon,
	Navigation01Icon,
	PaintBrush01Icon,
	RefreshIcon,
	RepeatIcon,
	Robot01Icon,
	Search01Icon,
	Settings01Icon,
	Shield01Icon,
	SidebarLeftIcon,
	SortByUp01Icon,
	Sun01Icon,
	Table01Icon,
	Tag01Icon,
	TextCheckIcon,
	TextFontIcon,
	Timer01Icon,
	UserCircleIcon,
} from "@hugeicons/core-free-icons";

type SettingIcon = typeof Settings01Icon;

const SETTING_ICONS: Record<string, SettingIcon> = {
	"general-license": LicenseIcon,
	"general-trial-status": Timer01Icon,
	"general-activated": CheckmarkCircle02Icon,
	"general-license-key": Key01Icon,
	"general-activate-glyph": Certificate01Icon,
	"general-official-build": Shield01Icon,
	"general-license-help": HelpCircleIcon,
	"general-language": LanguageSquareIcon,
	"general-date-format": Calendar03Icon,
	"general-resume-last-session": RefreshIcon,
	"appearance-theme-mode": Moon02Icon,
	"appearance-light-theme": Sun01Icon,
	"appearance-dark-theme": Moon02Icon,
	"appearance-translucent-app": BrowserIcon,
	"appearance-accent": ColorPickerIcon,
	"appearance-light-theme-colors": PaintBrush01Icon,
	"appearance-dark-theme-colors": PaintBrush01Icon,
	"appearance-interface-font": TextFontIcon,
	"appearance-monospace-font": CodeIcon,
	"appearance-editor-font": TextFontIcon,
	"appearance-ui-font-size": TextFontIcon,
	"appearance-editor-font-size": TextFontIcon,
	"shortcuts-customize": KeyboardIcon,
	"shortcuts-search": Search01Icon,
	"shortcuts-workspace": Folder01Icon,
	"shortcuts-navigation": Navigation01Icon,
	"shortcuts-search-category": Search01Icon,
	"shortcuts-file-operations": File01Icon,
	"shortcuts-tabs": BrowserIcon,
	"shortcuts-ai": AiBrain01Icon,
	"shortcuts-editor": CommandIcon,
	"ai-features": AiBrain01Icon,
	"ai-configuration": Settings01Icon,
	"ai-provider-service": CloudIcon,
	"ai-provider-model": Robot01Icon,
	"ai-reasoning-level": AiBrain01Icon,
	"ai-base-url": Link01Icon,
	"ai-local-network": Globe02Icon,
	"ai-api-key": Key01Icon,
	"ai-chatgpt-account": UserCircleIcon,
	"ai-chatgpt-identity": UserCircleIcon,
	"ai-chatgpt-authentication": Shield01Icon,
	"ai-chatgpt-rate-limits": Timer01Icon,
	"space-daily-notes-folder": Calendar03Icon,
	"space-quick-notes-folder": Folder01Icon,
	"space-attachments-location": Attachment01Icon,
	"space-template-folder": Folder01Icon,
	"space-default-daily-template": FileEditIcon,
	"space-search-index-status": DatabaseSearchIcon,
	"space-search-index-people-tags": Tag01Icon,
	"git-availability": GitBranchIcon,
	"git-repository-state": GitCommitIcon,
	"git-how-it-works": InformationCircleIcon,
	"git-branch": GitBranchIcon,
	"git-automatic-sync": RepeatIcon,
	"git-sync-interval": Timer01Icon,
	"git-sync-actions": GitPullRequestIcon,
	"git-conflict-policy": GitMergeIcon,
	"git-include-templates": FileEditIcon,
	"git-include-attachments": Attachment01Icon,
	"git-include-non-markdown": File01Icon,
	"general-editor-table-of-contents": ListViewIcon,
	"general-editor-frontmatter": CodeIcon,
	"general-editor-colorful-headings": HeadingIcon,
	"appearance-editor-presentation-beautiful-tags": Tag01Icon,
	"appearance-editor-presentation-width": Layout01Icon,
	"general-editor-collapsible-headings": HeadingIcon,
	"general-editor-collapsible-lists": ListViewIcon,
	"general-editor-spell-check": TextCheckIcon,
	"general-editor-vim-mode": CommandIcon,
	"ai-assistant-behavior-tools": Robot01Icon,
	"appearance-layout-folio-mode": BookOpen01Icon,
	"appearance-layout-classic-all-notes": SidebarLeftIcon,
	"general-file-tree-folder-counts": Folder01Icon,
	"general-file-tree-non-markdown-files": File01Icon,
	"general-file-tree-sort": SortByUp01Icon,
	"appearance-database-column-color": Table01Icon,
	"about-app": InformationCircleIcon,
	"about-website": Globe02Icon,
	"about-discord": DiscordIcon,
	"about-terms": Agreement01Icon,
	"about-privacy": Shield01Icon,
	"about-updates": CloudDownloadIcon,
	"about-alpha-releases": Megaphone01Icon,
	"about-license-status": LicenseIcon,
	"about-community-build": CodeIcon,
	"about-update-status": CircleArrowReload01Icon,
	"about-changelog": GitCompareIcon,
};

export function getPaletteSettingIcon(settingId: string | undefined) {
	return settingId
		? (SETTING_ICONS[settingId] ?? Settings01Icon)
		: Settings01Icon;
}
