import {
	AiBrain01Icon,
	Attachment01Icon,
	BookOpen01Icon,
	BrowserIcon,
	Calendar03Icon,
	CodeIcon,
	CommandIcon,
	DatabaseSearchIcon,
	File01Icon,
	Folder01Icon,
	HeadingIcon,
	LanguageSquareIcon,
	Layout01Icon,
	ListViewIcon,
	Megaphone01Icon,
	Moon02Icon,
	RefreshIcon,
	Robot01Icon,
	Settings01Icon,
	SidebarLeftIcon,
	SortByUp01Icon,
	Sun01Icon,
	Table01Icon,
	Tag01Icon,
	TextCheckIcon,
	TextFontIcon,
} from "@hugeicons/core-free-icons";

type SettingIcon = typeof Settings01Icon;

const SETTING_ICONS: Record<string, SettingIcon> = {
	"general-language": LanguageSquareIcon,
	"general-date-format": Calendar03Icon,
	"general-resume-last-session": RefreshIcon,
	"appearance-theme-mode": Moon02Icon,
	"appearance-light-theme": Sun01Icon,
	"appearance-dark-theme": Moon02Icon,
	"appearance-translucent-app": BrowserIcon,
	"appearance-interface-font": TextFontIcon,
	"appearance-editor-font": TextFontIcon,
	"appearance-monospace-font": CodeIcon,
	"appearance-ui-font-size": TextFontIcon,
	"appearance-editor-font-size": TextFontIcon,
	"ai-features": AiBrain01Icon,
	"ai-assistant-behavior-tools": Robot01Icon,
	"space-daily-notes-folder": Calendar03Icon,
	"space-quick-notes-folder": Folder01Icon,
	"space-attachments-location": Attachment01Icon,
	"space-template-folder": Folder01Icon,
	"space-search-index-status": DatabaseSearchIcon,
	"general-editor-table-of-contents": ListViewIcon,
	"general-editor-frontmatter": CodeIcon,
	"general-editor-colorful-headings": HeadingIcon,
	"appearance-editor-presentation-beautiful-tags": Tag01Icon,
	"appearance-editor-presentation-width": Layout01Icon,
	"general-editor-collapsible-headings": HeadingIcon,
	"general-editor-collapsible-lists": ListViewIcon,
	"general-editor-spell-check": TextCheckIcon,
	"general-editor-vim-mode": CommandIcon,
	"appearance-layout-folio-mode": BookOpen01Icon,
	"appearance-layout-classic-all-notes": SidebarLeftIcon,
	"general-file-tree-folder-counts": Folder01Icon,
	"general-file-tree-non-markdown-files": File01Icon,
	"general-file-tree-sort": SortByUp01Icon,
	"appearance-database-column-color": Table01Icon,
	"about-alpha-releases": Megaphone01Icon,
};

export function getPaletteSettingIcon(settingId: string | undefined) {
	return settingId
		? (SETTING_ICONS[settingId] ?? Settings01Icon)
		: Settings01Icon;
}
